name: app
description: "The Jay app with flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.3+440

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Arch
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  equatable: ^2.0.5
  meta: ^1.10.0

  # Networking
  dio: ^5.4.0
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1

  # Storage
  shared_preferences: ^2.2.2

  # Maps
  google_maps_flutter: ^2.9.0

  # Navigation
  go_router: ^13.2.0

  # UI
  fluttertoast: ^8.2.4
  flutter_local_notifications: ^17.2.2

  # Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

  # Utils
  url_launcher: ^6.2.4
  package_info_plus: ^8.0.2
  device_info_plus: ^9.1.2
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3

  #sentry
  sentry_flutter: ^8.9.0

  #onesignal
  onesignal_flutter: ^5.2.4

  # TTS
  flutter_tts: ^3.8.5

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: any

dependency_overrides:
  win32: 3.0.0
  win32_registry: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/jay-logo.png
    - assets/firefighter-avatar.svg
    - assets/megaphone.svg
    - assets/sleeping.svg
    - assets/plan-domu.pdf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
